# Generated by Django 5.2.1 on 2025-05-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_goals',
            field=models.TextField(blank=True, help_text='Career aspirations for AI guidance'),
        ),
        migrations.AddField(
            model_name='user',
            name='domain',
            field=models.CharField(blank=True, help_text='Learning domain/field', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, help_text='Learning interests for AI recommendations', max_length=500),
        ),
    ]
