# Generated by Django 5.2.1 on 2025-05-28 02:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="User's email for notifications", max_length=254)),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')], help_text='Overall rating of the app (1-5 stars)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(choices=[('ui_ux', 'User Interface & Experience'), ('performance', 'Performance & Speed'), ('features', 'Features & Functionality'), ('support', 'Customer Support'), ('payment', 'Payment System'), ('video_quality', 'Video Quality'), ('mobile', 'Mobile Experience'), ('general', 'General Feedback')], default='general', help_text='Category of feedback', max_length=20)),
                ('title', models.CharField(help_text='Brief title for the feedback', max_length=200)),
                ('message', models.TextField(help_text='Detailed feedback message')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Under Review'), ('replied', 'Admin Replied'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='pending', help_text='Current status of the feedback', max_length=20)),
                ('admin_reply', models.TextField(blank=True, help_text="Admin's reply to the feedback", null=True)),
                ('reply_sent_via_email', models.BooleanField(default=False, help_text='Whether reply was sent via email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User's browser/device info")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured feedback for testimonials')),
                ('is_public', models.BooleanField(default=True, help_text='Show in public feedback')),
                ('admin_user', models.ForeignKey(blank=True, help_text='Admin who replied to this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_feedback_replies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Feedback',
                'verbose_name_plural': 'App Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_feedback', 'New Feedback Received'), ('admin_reply', 'Admin Reply Sent'), ('status_update', 'Status Updated')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.appfeedback')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appfeedback',
            index=models.Index(fields=['rating', 'created_at'], name='users_appfe_rating_1c5f39_idx'),
        ),
        migrations.AddIndex(
            model_name='appfeedback',
            index=models.Index(fields=['status', 'created_at'], name='users_appfe_status_9d9810_idx'),
        ),
        migrations.AddIndex(
            model_name='appfeedback',
            index=models.Index(fields=['category', 'rating'], name='users_appfe_categor_c4368c_idx'),
        ),
    ]
