# Generated by Django 5.2.1 on 2025-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'Programming & Development'), ('data-science', 'Data Science & Analytics'), ('web-development', 'Web Development'), ('mobile-development', 'Mobile Development'), ('ai-ml', 'AI & Machine Learning'), ('design', 'UI/UX Design'), ('business', 'Business & Marketing'), ('language', 'Language Learning'), ('music', 'Music & Arts'), ('fitness', 'Health & Fitness'), ('other', 'Other')], help_text='Session category for recommendations', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in INR, null for free sessions', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills for ML matching'),
        ),
        migrations.AddField(
            model_name='session',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Session cover image', null=True, upload_to='session_thumbnails/'),
        ),
    ]
