# Generated by Django 5.2.1 on 2025-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_sessions",
            "0002_session_category_session_price_session_skills_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_ready",
            field=models.BooleanField(default=False),
        ),
    ]
