# Generated by Django 5.2.1 on 2025-06-17 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_sessions", "0003_booking_is_ready"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="attendance_duration",
            field=models.IntegerField(
                blank=True, help_text="Attendance duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="content_relevance",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="mentor_effectiveness",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="session_quality",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="technical_quality",
            field=models.IntegerField(
                blank=True,
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="feedback_requested",
            field=models.CharField(
                choices=[
                    ("session_reminder", "Session Reminder"),
                    ("session_starting", "Session Starting"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("session_cancelled", "Session Cancelled"),
                    ("new_request", "New Request"),
                    ("request_accepted", "Request Accepted"),
                    ("request_rejected", "Request Rejected"),
                    ("new_message", "New Message"),
                    ("payment_received", "Payment Received"),
                    ("session_started", "Session Started"),
                    ("session_ended", "Session Ended"),
                    ("feedback_requested", "Feedback Requested"),
                ],
                default="session_reminder",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="actual_duration",
            field=models.IntegerField(
                blank=True, help_text="Actual session duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="allow_late_join",
            field=models.BooleanField(
                default=True, help_text="Allow learners to join after session starts"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="auto_start",
            field=models.BooleanField(
                default=False, help_text="Automatically start session at scheduled time"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="require_approval",
            field=models.BooleanField(
                default=False, help_text="Require mentor approval for bookings"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Session cover image",
                null=True,
                upload_to="session_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("attended", "Attended"),
                    ("no_show", "No Show"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_mentor", models.BooleanField(default=False)),
                (
                    "connection_status",
                    models.CharField(default="connected", max_length=20),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_participants",
                        to="learning_sessions.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("session", "user")},
            },
        ),
    ]
