# Generated by Django 5.2.1 on 2025-06-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning_sessions",
            "0004_booking_attendance_duration_booking_joined_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessionparticipant",
            options={"ordering": ["-joined_at"]},
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="audio_level",
            field=models.FloatField(
                default=1.0, help_text="Audio volume level (0.0 to 1.0)"
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="bandwidth",
            field=models.FloatField(
                default=0.0, help_text="Available bandwidth in Mbps"
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="is_recording",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="is_screen_sharing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="is_video_off",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="latency",
            field=models.FloatField(default=0.0, help_text="Latency in milliseconds"),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="network_quality",
            field=models.CharField(
                choices=[
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                    ("Poor", "Poor"),
                ],
                default="High",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="packet_loss",
            field=models.FloatField(default=0.0, help_text="Packet loss percentage"),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="preferred_audio_device",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="preferred_video_device",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="reconnection_count",
            field=models.IntegerField(default=0, help_text="Number of reconnections"),
        ),
        migrations.AddField(
            model_name="sessionparticipant",
            name="total_connection_time",
            field=models.IntegerField(
                default=0, help_text="Total connection time in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="sessionparticipant",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("connected", "Connected"),
                    ("disconnected", "Disconnected"),
                    ("reconnecting", "Reconnecting"),
                    ("connecting", "Connecting"),
                ],
                default="connected",
                max_length=20,
            ),
        ),
    ]
