# Generated by Django 5.2.1 on 2025-06-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_sessions", "0005_alter_sessionparticipant_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="feedback_requested",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("session_reminder", "Session Reminder"),
                    ("session_starting", "Session Starting"),
                    ("booking_confirmed", "Booking Confirmed"),
                    ("session_cancelled", "Session Cancelled"),
                    ("new_request", "New Request"),
                    ("request_accepted", "Request Accepted"),
                    ("request_rejected", "Request Rejected"),
                    ("new_message", "New Message"),
                    ("payment_received", "Payment Received"),
                    ("session_started", "Session Started"),
                    ("session_ended", "Session Ended"),
                    ("feedback_requested", "Feedback Requested"),
                    ("mentor_ready", "Mentor Ready"),
                    ("learner_ready", "Learner Ready"),
                    ("mentor_ready_status", "Mentor Ready Status"),
                ],
                max_length=50,
            ),
        ),
    ]
