services:
  - type: web
    name: peerlearn-app             # Must match name you’ll pick on Render
    env: python
    region: oregon                  # Same region as your DB
    plan: free
    repo: https://github.com/ANANDU-2000/PeerlearnProject
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: |
      gunicorn peerlearn.wsgi:application
    envVars:
    - key: SECRET_KEY
      value: "your‑secret‑key"
    - key: DEBUG
      value: "False"
    - key: ALLOWED_HOSTS
      value: "peerlearn-app.onrender.com peerlearnproject.onrender.com"
    - key: SENDGRID_API_KEY
      value: "SG.xxxx"
    - key: DEFAULT_FROM_EMAIL
      value: "no-reply@yourdomain.com"
    # DATABASE_URL will be auto‑injected

