services:
  - type: web
    name: peerlearn-platform
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput --clear
      python manage.py migrate --noinput
    startCommand: |
      gunicorn --bind 0.0.0.0:$PORT --workers 4 peerlearn.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: "peerlearn.settings"
      - key: PYTHON_VERSION
        value: "3.13"
      - key: REDIS_URL
        fromService:
          type: redis
          name: peerlearn-redis
          property: connectionString
databases:
  - name: peerlearn-redis
    type: redis
    region: oregon