services:
  - type: web
    name: peerlearn-platform
    env: python
    region: oregon
    plan: starter
    repo: https://github.com/ANANDU-2000/PeerlearnProject
    branch: main
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: |
      gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 peerlearn.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "peerlearn-platform.onrender.com,localhost,127.0.0.1"
      - key: DJANGO_SETTINGS_MODULE
        value: "peerlearn.settings"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_JTeqXMBguhg25H"
      - key: RAZORPAY_KEY_SECRET
        value: "7FYtozDO4Tb6w0aEZwYtc6DB"
      - key: SENDGRID_API_KEY
        value: "SG.your_sendgrid_key"
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@peerlearn.com"
      - key: STRIPE_PUBLISHABLE_KEY
        value: "pk_test_xxxxxxxxxxxxxxxx"
      - key: STRIPE_SECRET_KEY
        value: "sk_test_xxxxxxxxxxxxxxxx"
      - key: WEBRTC_STUN_SERVERS
        value: "stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302"
