# Generated by Django 5.2.1 on 2025-05-25 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning_sessions", "0003_booking_is_ready"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('session', 'Session'), ('mentor', 'Mentor'), ('skill', 'Skill')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('score', models.FloatField()),
                ('reasoning', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'type'], name='recommendat_user_id_3f4b8c_idx'), models.Index(fields=['score'], name='recommendat_score_e8f5b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('viewed', 'Viewed'), ('clicked', 'Clicked'), ('dismissed', 'Dismissed'), ('bookmarked', 'Bookmarked')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="learning_sessions.session")),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
